### ISSUE TITLE
{"code":"ImATeapotError","message":"This is an API endpoint. Please consult https://chainpoint.org"}

### ISSUE THREAD

**Issue by mathcpp** [chainpoint/chainpoint-node#14]
OS:new ubuntu 16.04 x64
after ` make up make down make clean all` it comes the error  "{"code":"ImATeapotError","message":"This is an API endpoint. Please consult https://chainpoint.org"}"
https://a.chainpoint.org/nodes/0x-my-address comes that `{"code":"MethodNotAllowedError","message":"GET is not allowed"}`
docker ps:
`quay.io/chainpoint/chainpoint-node:3ace0ebadf3cb69fecaac0aed4f24f1bd5f16c8b`

**Comment by grempe** [comment]
The root `/` URL returns the API endpoint message by design.

Try /config to ensure public operation.

The `/nodes/0x...` endpoint was removed today after a security concern was raised. There is now an alternative mechanism in the FAQ:

https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions
