### ISSUE TITLE
Failing all test on multiple instances

### ISSUE THREAD

**Issue by oinked2k** [chainpoint/chainpoint-node#2]
Following your guide on multiple AWS EC2 instances, still by checking https://a.chainpoint.org/nodes/<eth address> i get 

> "public_ip_test":false,"time_test":false,"calendar_state_test":false,"minimum_credits_test":true}

on all 4 nodes. Log seems fine, 
`chainpoint-node_1  | 2017-09-17T09:34:55.627488937Z CoreHost selected from DNS : c.chainpoint.org
chainpoint-node_1  | 2017-09-17T09:34:55.715936520Z Successfully established Postgres connection
chainpoint-node_1  | 2017-09-17T09:34:55.730689869Z Using existing NodeHMAC for TNT address x
chainpoint-node_1  | 2017-09-17T09:34:56.360854012Z Node registration confirmed and updated
chainpoint-node_1  | 2017-09-17T09:34:56.360878843Z Using private auth key (back me up!)`

**Comment by grempe** [comment]
Your system appears to be unavailable from the public Internet `"public_ip_test":false`. If so, the time and calendar tests would also fail since we can't reach your host to verify them. Please look into whether your host is available from an outside host. You should be able to reach:

http://your-server-ip-address/config
