### ISSUE TITLE
Sent all TNT to be used as Credit, is wallet still eligible?

### ISSUE THREAD

**Issue by Euroanchor** [chainpoint/chainpoint-node#30]
Sent all TNT to be used as Credit, is wallet still eligible?

Please engage with your supporters on Reddit so we don't clutter up your Github

https://www.reddit.com/r/tierion/comments/70qonh/constructive_ideas_go_here/?sort=new

My suggestion:-
Ok first, remove the 2500 wallet deposit requirement.
Or, give us one single possible rationale for its existence.
I understand (but don't agree with) the credit system, and it is good to have some sort of cost involved to prevent spamming etc.
But the lower the entry requirements the more nodes you will have. The more nodes you have, the stronger the network will be. If the deposited TNT needed to be turned into credits, this too I would understand. Then it could be held as a ransom, if a node started misbehaving they would forfeit the credits. Or if you were worried about the credit system temporarily being offline, then having all TNT turned into credits would build a cushion of reserve.
But the requirement to have 2500 in a wallet serves quite literally no purpose, other than to raise the price of the coin.
A coin which we then need to burn /sell back to you to secure your network. And then no fixed amount or timetable as to how fast the credits will be burned

**Comment by reinto** [comment]
Having collateral makes sense, either by having credits or TNT.
The value in having TNT as collateral, imo, is you can send it to another wallet when your node is down or corrupt. Using a minimum amount for credits to be eligible for rewards makes it all more flexible.
This is also important for other reasons: I've seen nodes being setup, using ETH addresses not owned by the owner node. After registering the node and getting the secret, the node will be taken offline. This will eliminate the owner of the address to actually set up a node, because the address is already in use, but not eligible, because it is down. There are some flaws in the design that allow hackers to dominate the nodes... Unfortunately.

**Comment by grempe** [comment]
This is not a bug.

The purpose for maintaining a minimum balance of TNT is to ensure that Node operators have some stake for every Node they operate. We do not need, or even desire, an infinite number of Nodes.

We will have some updates to the credit model. We have temporarily suspended the need to submit TNT for credits and are topping up all accounts with the max credits needed for daily operation. Please see the README for updates.
