### ISSUE TITLE
exit code 137

### ISSUE THREAD

**Issue by paOol** [chainpoint/chainpoint-node#46]
> chainpoint-node_1  | 2017-09-20T22:58:01.204657885Z Validated and stored Core blocks 46100 to 46199
> chainpoint-node_1  | 2017-09-20T22:58:24.666519055Z Killed
> chainpoint-node_1  | 2017-09-20T22:58:24.670308952Z error Command failed with exit code 137.

on the latest version with `git pull`

**Comment by grempe** [comment]
https://bobcares.com/blog/error-137-docker/

**Comment by ken0509** [comment]
I checked the URL, but I am afraid I can't understand how to fix code 137 except adding more RAM.
What should I do to optimize the server or do other ways? Please kindly explain a concrete way.

In addition, is there no chance to get reward when code 137 showing?
If so, I want to fix it as soon as possible...

**Comment by koheihamada** [comment]
ive got same problem...

**Comment by Chikashi-Kato** [comment]
I don't think this code 137 error is same as docker's error 137 which indicates the lack of host memory. In my case, zombi container occupied the docker network and it caused the code 137 error in the `chainpoint-node` container.
I could fix the issue as following:

1.  Excuse `make down` and check if it fails with network removal. If it's not network related, the root cause of the issue isn't same as mine.
2. Remove all of the running container by `docker container rm -f` and make sure there is no running container after this step. (You can check running container by `docker container ls` command
3. `docker network inspect chainpointnode_chainpoint-node` and check `containers` section. If it's not blank, write down the name of the container
4. `docker network disconnect -f chainpointnode_chainpoint-node [container_name]` to disconnect the zombi container (Replace [container_name] with the name you wrote down in step 3)
5. `docker network rm chainpointnode_chainpoint-node`
6. `make up`

I wish this helps :)

**Comment by n0bility6** [comment]
Try to do this, mine worked.

Create Swap File

dd if=/dev/zero of=/mnt/myswap.swap bs=512K count=2000    //1GB Swap
mkswap /mnt/myswap.swap
swapon /mnt/myswap.swap

nano /etc/fstab
/mnt/myswap.swap none swap sw 0 0

**Comment by ken0509** [comment]
Thank you. In my case, I have solved it with SWAP setting.
