### ISSUE TITLE
Error while performing daily Auto-restart

### ISSUE THREAD

**Issue by biganth** [chainpoint/chainpoint-node#75]
Saw this in my log. Node restarted without any errors.

```
INFO : App : Performing daily Auto-restart...
chainpoint-node    | 2017-10-14T02:20:18.338488611Z error Command failed with exit code 1.
chainpoint-node    | 2017-10-14T02:20:18.340025181Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by n0bility6** [comment]
try to update your node. new version of chainpoint is released.

**Comment by biganth** [comment]
Node is already running ver 1.2.0:

http://128.199.252.250/config

**Comment by grempe** [comment]
This is not actually bug. Nodes now schedule an automatic restart at a random time each day. They do this in order to pick up the latest Firewall IP list and incorporate it. This cannot be done to the running server. Before restart the Node verifies it has no hashes in progress, and turns off incoming hashes. This restart process takes just a few seconds once per day and is totally automatic. We can perhaps improve the messaging around this and I'll take that as a todo.
