### ISSUE TITLE
wont't run on macOS Sierra

### ISSUE THREAD

**Issue by kiahmed** [chainpoint/chainpoint-node#77]
Hi,
It says it runs on macOS , but unfortunately couldn't make it run on mine. The postgresql container won't start no matter what. It looks like a common permission/volume issue between  docker vm and local filesystem. Tried giving full permission to that mounted location, but no luck. Are you aware of that..any help would be appreciated..get this error:
2017-11-16T02:06:04.201942657Z 
fixing permissions on existing directory /var/lib/postgresql/data ... ok
initdb: could not create directory "/var/lib/postgresql/data/pg_xlog": Permission denied
initdb: removing contents of data directory "/var/lib/postgresql/data"

**Comment by grempe** [comment]
Well, this would be most surprising to be a bug since we have done *all* development for the Nodes on macOS Sierra and High Sierra. :-)

The directory path you reference is actually a path inside the Docker container and not one on your local macOS filesystem.

The Postgres data is mounted from a local volume by Docker. We store all data for Redis and PostgreSQL in the `.../chainpoint-node/.data` directory. I am suspecting that somehow you have a permissions issue on your machine for that directory or a subdirectory under it. You might back up your HMAC key, delete that entire `.data` directory, and then restore that key (instructions are in the FAQ).

This could also be related to your local macOS Docker installation perhaps.

**Comment by grempe** [comment]
Closing this as it is clear that the Node can run on all recent versions of macOS as that is the development platform. If you feel this is in error please let me know, with additional supporting details to support a bug report, and I'll re-open.

**Comment by kiahmed** [comment]
ofcourse it generates the following error. This directory /chainpoint-node/.data is owned by the current user that . I already had docker toolbox installed on that machine tho. Could you suggest any workaround that I can change in the docker-compose file?

chainpoint-node    | 2017-11-16T20:07:54.876445396Z PostgreSQL : not available : Will retry in 5 seconds...

**Comment by grempe** [comment]
Are all subdirectories of `.data` also owned by the use running the process? Please send the output of `la -laR .data` when run from within your chainpoint-node dir.

Can you share the full output of `make logs-postgres` or `make logs-all`

Can you share the full output of `ps aux | grep -i post`

Can you cleanly clone the `chainpoint-node` repository into a new directory and try running it from there? And provide output if errors.

We only support the official packaged install of Docker, which includes docker-compose for macOS. 

There is nothing that should require change in the `docker-compose.yaml` file that I can see from the limited info you have provided.

**Comment by grempe** [comment]
Please also provide the output of `docker --version` and `docker-compose --version`
