### ISSUE TITLE
The port scanning showed that the status of 80 port was closed when I started the chain node, was it ok?

### ISSUE THREAD

**Issue by bizhonggeng** [chainpoint/chainpoint-node#81]
The port scanning showed that the status of 80 port was still closed after I started the chain node using "make up". I founded that there was a port mapping, transferring from 80 port to 8080 port as below:

```
     Name                    Command               State          Ports
-------------------------------------------------------------------------------
chainpoint-node   su-exec node:node /sbin/ti ...   Up      0.0.0.0:80->8080/tcp
postgres-node     docker-entrypoint.sh postgres    Up      5432/tcp
redis-node        docker-entrypoint.sh redis ...   Up      6379/tcp
```

Was that right? 
The port 80 and 22 were exposed publicly. I was sure that the URL where my node applied can be publicly discovered and utilized by others.

**Comment by grempe** [comment]
The port mapping you referenced is internal to Docker (port 80 on the Docker host is being mapped to port 8080 on the `chainpoint-node` container).

You should test your Node is available via its public URI by visiting `http://[IP]/config` from another host.  If it is not available it means that you have port blocking on the host or from your service provider. Closing as this is a system or ISP level issue, not a Node issue. Please re-open if you have any reason to believe otherwise and please provide documentation and logs of that if thats the case.

**Comment by 001dingo** [comment]
I have this issue too. Port 80 is open. To make sure I started apache and connected to port 80 publicly from another host.

Here are the steps:
1. Create fresh Ubuntu 16.04 LTS server with inbound 80 open to any ip
2. Run install command from ReadMe
3. Make up
4. Edit .env file with token address and IP
5. Make upgrade
5. Unable to access public ip http://[ip]/config (connection refused, port closed).

Are others having this problem with a fresh install?

**Comment by grempe** [comment]
Thanks for the additional report @001dingo 

Please open a new bug if this problem is continuing. Please include the logfiles (with reg key redacted), from the full startup sequence in that new report.
