### ISSUE TITLE
Node not working after getting an SSL cert for its IP

### ISSUE THREAD

**Issue by arisAlexis** [chainpoint/chainpoint-node#99]
I wanted to run a simple nodejs app in the same node that Chainpoint is running so I got a Letsencrypt certificate for this address. I changed nothing else in any other configuration and the node was running normally.

Then at some point make logs reports this:

> chainpoint-node    | 2018-11-09T16:20:54.801685493Z ERROR : App : Startup : RequestError: Error: Hostname/IP doesn't match certificate's altnames: "Host: a.chainpoint.org. is not in the cert's altnames: DNS:api.mmm3.com"

`curl -v https://a.chainpoint.org` connectes correctly.

make upgrade finishes without errors and make up too. 

Apparently the codebase is a bit confused with the IP resolving to something else.

**Comment by arisAlexis** [comment]
Yes true so there is something going on because you can see the message from your codebase finding my DNS name for this IP and mentioning the word cert. 

I never changed any files from the chainpoint folder and as previously said it was running seamlessly. I understand that repeating these steps are important for new users though so here it is:

#####################################################################
# Chainpoint Node Configuration
#####################################################################

# A valid Ethereum address that has been assigned the minimum
# balance of TNT tokens required to operate a Node.
#
# An address that does not meet the minumum balance is ineligible
# for TNT rewards for Nodes. A valid Ethereum address has
# 40 hex ([0-9a-fA-F]) characters preceded by `0x`.
#
# EXAMPLES:
#
#  YES   : 0x4205fC28a8Bb5E6199717cAFdE36507aB4F91EE4
#
#  NO!   : 4205fC28a8Bb5E6199717cAFdE36507aB4F91EE4
#
#  NO!   : 4205fC28
#

NODE_TNT_ADDRESS=0x8160Ecb4450f4277e9B15CFC9fE1E8c3531560a1

# A URI with an IPv4 Address [OPTIONAL]
#
# IMPORTANT : Don't forget the 'http://' prefix!
#
# Private IP Address Space IP Addresses:
#
# If you provide an IP address that is in the RFC1918 Private
# address space shown below, your Node will operate properly, but it
# will not be audited, as it will not be publicly available.
# It also won't be eligible for TNT rewards.
#
# 10.0.0.0    – 10.255.255.255
# 172.16.0.0  – 172.31.255.255
# 192.168.0.0 – 192.168.255.255
#
# The same applies for special addresses 0.0.0.0 and 127.0.0.1
#
# You can also leave this value empty if you don't want to advertise
# your Node publicly.
#
# EXAMPLES:
#
#  YES  : http://123.456.789.123          # Will be publicly advertised
#
#  OK   : http://10.0.1.2                 # Will NOT be publicly advertised (RFC 1918 private address)
#
#  NO!  : http://mynode.example.com       # DNS domain names are not allowed
#
#  NO!  : 123.456.789.123                 # Missing URI scheme [http, https] are not allowed
#

CHAINPOINT_NODE_PUBLIC_URI=http://95.179.151.3

#####################################################################
# OPTIONAL SETTINGS
#####################################################################


# Node Web Console
# A web based Node dashboard is available at http://NODE_IP/
#
# By default, the password for this dashboard is set to the same
# value as the NODE_TNT_ADDRESS set above.
#
# Optionally you may specify a custom password to access it by
# uncommenting and setting the CHAINPOINT_NODE_UI_PASSWORD variable
# below to a password of your choice. Allows characters [a-zA-Z0-9]
#
# Alternatively, you can make your Node's dashboard available to the
# public, with no password required, by setting this value to 'false'
#
# EXAMPLES:
#
#   CHAINPOINT_NODE_UI_PASSWORD=foobar
#   CHAINPOINT_NODE_UI_PASSWORD=false
#
#CHAINPOINT_NODE_UI_PASSWORD=

**Comment by grempe** [comment]
The first issue to resolve is that this node is not accessible from the public Internet on port 80 at the IP address provided in the config.

```
$ curl -i http://95.179.151.3/
curl: (7) Failed to connect to 95.179.151.3 port 80: Connection refused
```

You need to open port 80 on that host in any firewall you may have in place, and be running the Node on that port.

Regarding your other reported issue. `a.chainpoint.org` is configured correctly and serving traffic using its appropriate certificate.

```
sslscan a.chainpoint.org
Version: 1.11.12-static
OpenSSL 1.0.2f  28 Jan 2016

Connected to 104.16.195.223

Testing SSL server a.chainpoint.org on port 443 using SNI name a.chainpoint.org

  TLS Fallback SCSV:
Server supports TLS Fallback SCSV

  TLS renegotiation:
Secure session renegotiation supported

  TLS Compression:
Compression disabled

  Heartbleed:
TLS 1.2 not vulnerable to heartbleed
TLS 1.1 not vulnerable to heartbleed
TLS 1.0 not vulnerable to heartbleed

  Supported Server Cipher(s):
Preferred TLSv1.2  128 bits  ECDHE-ECDSA-AES128-GCM-SHA256 Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-ECDSA-AES128-SHA        Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-ECDSA-AES128-SHA256     Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-ECDSA-AES256-GCM-SHA384 Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-ECDSA-AES256-SHA        Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-ECDSA-AES256-SHA384     Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256
Accepted  TLSv1.2  128 bits  AES128-SHA
Accepted  TLSv1.2  128 bits  AES128-SHA256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384
Accepted  TLSv1.2  256 bits  AES256-SHA
Accepted  TLSv1.2  256 bits  AES256-SHA256
Preferred TLSv1.1  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  128 bits  AES128-SHA
Accepted  TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  256 bits  AES256-SHA
Preferred TLSv1.0  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  128 bits  AES128-SHA
Accepted  TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  256 bits  AES256-SHA
Accepted  TLSv1.0  112 bits  DES-CBC3-SHA

  SSL Certificate:
Signature Algorithm: ecdsa-with-SHA256
Subject:  chainpoint.org
Altnames: DNS:chainpoint.org, DNS:*.chainpoint.org, DNS:*.nodes.chainpoint.org
Issuer:   CloudFlare Inc ECC CA-2

Not valid before: Aug 11 00:00:00 2018 GMT
Not valid after:  Aug 11 12:00:00 2019 GMT
```

I'm not sure why your server is reporting a TLS SNI mismatch with `altnames: DNS:api.mmm3.com`. This is very suspicious. Do you have entries in your local `hosts` file that is overriding IP lookups?

We only attempt to make a connection to the same URI you have configured in your `.env` file. There should be no DNS resolution taking place there as we're connecting directly to an IP address. Also, we normally only make an `http` request, and not an `https` request, so certificates would never come into play.

I suspect there is something else you have getting in the way here, and I don't understand what it is you are really trying to do.

In any case any such custom config is not something that we can support. I will close this issue for now since there is no identified bug, please feel free to re-open if you identify an issue in the Node's code that is the root cause of an issue you are having.

Cheers

**Comment by arisAlexis** [comment]
> The first issue to resolve is that this node is not accessible from the public Internet on port 80 at the IP address provided in the config.

OK please don't close tickets so eagerly before you understand the problem. The node *EXITS* so of course it's not accessible on port 80, that was the problem in the first place. The node was running for months OK and then stopped without doing anything else than getting a letsencrypt cert and putting an DNS A record for that IP.

**Comment by grempe** [comment]
Happy to re-open. Please note, you made no mention of adding a DNS `A` record in any earlier part of this report.

And, yes, the Node exits when it is self-unreachable at the public URI in it's config. This is to eliminate issues that we saw on many nodes when mis-configured. 

If you believe that this issue is solely the result of adding a DNS record to the IP have you tried removing only that `A` record and restarting the Node?  Does that resolve the issue and allow the node to start and continue running?

If you'd like to provide any non-public info about the node that would be helpful you can send it to support@tierion.com with a link to this bug report.

Cheers

**Comment by filoozom** [comment]
I had a look at @arisAlexis' server with his permission, and the error I got was was simply related to an issue with Docker (or a configuration in general). To prove it, I simply ran `curl` from a base image:

```bash
# docker run --rm alpine sh -c "apk add --no-cache curl && curl -sS https://a.chainpoint.org"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/5) Installing ca-certificates (20171114-r3)
(2/5) Installing nghttp2-libs (1.32.0-r0)
(3/5) Installing libssh2 (1.8.0-r3)
(4/5) Installing libcurl (7.61.1-r1)
(5/5) Installing curl (7.61.1-r1)
Executing busybox-1.28.4-r1.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 6 MiB in 18 packages
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

This means that it's not because of Chainpoint's code base. Also, the issue was resolved after simply updating the server (`apt update && apt upgrade -y`) and rebooting. It might have been because of a kernel update without reboot, but I didn't really look into it further as it now works.

**Comment by grempe** [comment]
Will close as "not a bug". Thanks @filoozom for the assist which eliminated the Chainpoint Node server as the source of the issue.

I'd be curious to know:

* Was this server originally running the supported `Ubuntu 16.04 LTS` version? @filoozom mentioned a possible previously unreported Kernel upgrade and the need to perform an `apt upgrade -y` and reboot to resolve.
* Was this server also running an HTTPS proxy? Was the Node configured to operate behind this proxy (An unsupported configuration)? According to Google the `CONNECT_CR_SRVR_HELLO:wrong version number` issue seems to be often related to an old or mis-configured HTTP proxy.

In any case, it seems there was more to root cause of this issue than it simply "stopped without doing anything else than getting a letsencrypt cert and putting an DNS A record for that IP".

FYI, This node is now passing the last 4 audits today after the change. FYI, its history prior to this was very spotty. It has passed a total of `3237` and failed `3065` (~64 days worth) of audits. It had an audit score of `0` prior to today. So I think there has been an undiagnosed issue here for months.

Glad to hear it is perhaps resolved. 👍

**Comment by filoozom** [comment]
It is currently running `Ubuntu 16.04 LTS`, and based on the same research I checked `docker info` and it didn't appear to be using a proxy. Now, I guess there could be a proxy involved somewhere else but I didn't really pay close enough attention. 😕

**Comment by grempe** [comment]
Thanks for the update @filoozom, That's good to know.

**Comment by grempe** [comment]
Also making note, that the `nodeHeartbeat` function that self-checks the Node was added back in May 2018, and it makes an HTTP request directly to the Node URI specified in the `.env` file. Since it is an IPv4 URI there is no DNS lookup involved.

https://github.com/chainpoint/chainpoint-node-src/blob/3f34a7689cf7cfdc956e926437181f75f2ecd80a/server.js#L533

https://github.com/chainpoint/chainpoint-node-src/blob/3f34a7689cf7cfdc956e926437181f75f2ecd80a/server.js#L605
